# Generated by Django 5.0.3 on 2024-04-04 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0007_material_supplier_alter_material_bidding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_service', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='identificação do atendimento')),
                ('call', models.CharField(choices=[('05', 'VERBAL'), ('99', 'OUTROS'), ('02', 'TELEFONE'), ('03', 'EMAIL'), ('01', 'WHATSAPP'), ('04', 'PRESENCIAL')], default='02', max_length=2, verbose_name='tipo de atendimento')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('fullname_employee', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome completo do funcionario')),
                ('room', models.CharField(blank=True, max_length=20, verbose_name='sala referente')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('remote', models.BooleanField(default=False, verbose_name='remoto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('details', models.TextField(verbose_name='detalhes do atendimento')),
                ('pro_accountable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profissional_responsavel_atendimento', to=settings.AUTH_USER_MODEL, verbose_name='profissional responsável')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profissional_atendimento', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='setor', to='dashboard.sector', verbose_name='setor')),
            ],
            options={
                'verbose_name': 'atendimento',
                'verbose_name_plural': 'atendimentos',
                'ordering': ['-created_at', 'status', '-updated_at'],
            },
        ),
    ]
