# Generated by Django 5.0.3 on 2024-04-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='call',
            field=models.CharField(choices=[('99', 'OUTROS'), ('01', 'WHATSAPP'), ('05', 'VERBAL'), ('03', 'EMAIL'), ('04', 'PRESENCIAL'), ('02', 'TELEFONE')], default='02', max_length=2, verbose_name='Atendimento via'),
        ),
    ]
