# Generated by Django 5.0.3 on 2024-04-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='call',
            field=models.CharField(choices=[('01', 'WHATSAPP'), ('05', 'VERBAL'), ('99', 'OUTROS'), ('03', 'EMAIL'), ('02', 'TELEFONE'), ('04', 'PRESENCIAL')], default='02', max_length=2, verbose_name='atendimento via'),
        ),
        migrations.AlterField(
            model_name='service',
            name='room',
            field=models.CharField(blank=True, max_length=20, verbose_name='sala'),
        ),
    ]
