# Generated by Django 5.0.3 on 2024-05-06 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_alter_equipment_serial_number'),
        ('reports', '0006_alter_report_equipment'),
        ('services', '0008_alter_service_call_orderofservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofservice',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipments.equipment'),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='kind_order_of_service',
            field=models.CharField(choices=[('9B', 'OUTROS'), ('05', 'AGUARDANDO PEÇAS'), ('01', 'LIMPEZA'), ('02', 'REVISÃO DE EQUIPAMENTOS'), ('04', 'FORMATAÇÃO'), ('03', 'REVISÃO DE SERVIÇOS'), ('9A', 'AGUARDANDO TERCEIROS')], max_length=2, verbose_name='tipo do serviço'),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reports.report'),
        ),
        migrations.AlterField(
            model_name='service',
            name='call',
            field=models.CharField(choices=[('03', 'EMAIL'), ('99', 'OUTROS'), ('01', 'WHATSAPP'), ('04', 'PRESENCIAL'), ('05', 'VERBAL'), ('02', 'TELEFONE')], default='02', max_length=2, verbose_name='atendimento via'),
        ),
    ]
