# Generated by Django 5.0.3 on 2024-05-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_orderofservice_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='call',
            field=models.CharField(choices=[('02', 'TELEFONE'), ('05', 'VERBAL'), ('99', 'OUTROS'), ('01', 'WHATSAPP'), ('04', 'PRESENCIAL'), ('03', 'EMAIL')], default='02', max_length=2, verbose_name='atendimento via'),
        ),
        migrations.DeleteModel(
            name='OrderofService',
        ),
    ]
