# Generated by Django 5.0.3 on 2024-05-07 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_service'),
        ('services', '0013_alter_service_call_orderofservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderofservice',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reports.report'),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='kind_order_of_service',
            field=models.CharField(choices=[('04', 'FORMATAÇÃO'), ('01', 'LIMPEZA'), ('05', 'AGUARDANDO PEÇAS'), ('9A', 'AGUARDANDO TERCEIROS'), ('03', 'REVISÃO DE SERVIÇOS'), ('9B', 'OUTROS'), ('02', 'REVISÃO DE EQUIPAMENTOS')], max_length=2, verbose_name='tipo do serviço'),
        ),
        migrations.AlterField(
            model_name='service',
            name='call',
            field=models.CharField(choices=[('99', 'OUTROS'), ('05', 'VERBAL'), ('01', 'WHATSAPP'), ('03', 'EMAIL'), ('04', 'PRESENCIAL'), ('02', 'TELEFONE')], default='02', max_length=2, verbose_name='atendimento via'),
        ),
    ]
