# Generated by Django 5.0.3 on 2024-05-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_orderofservice_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofservice',
            name='kind_order_of_service',
            field=models.CharField(choices=[('01', 'LIMPEZA'), ('9A', 'AGUARDANDO TERCEIROS'), ('02', 'REVISÃO DE EQUIPAMENTOS'), ('03', 'REVISÃO DE SERVIÇOS'), ('04', 'FORMATAÇÃO'), ('9B', 'OUTROS'), ('05', 'AGUARDANDO PEÇAS')], max_length=2, verbose_name='tipo do serviço'),
        ),
        migrations.AlterField(
            model_name='service',
            name='call',
            field=models.CharField(choices=[('03', 'EMAIL'), ('05', 'VERBAL'), ('04', 'PRESENCIAL'), ('01', 'WHATSAPP'), ('02', 'TELEFONE'), ('99', 'OUTROS')], default='02', max_length=2, verbose_name='atendimento via'),
        ),
    ]
