# Generated by Django 5.0.3 on 2024-05-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_orderofservice_kind_order_of_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofservice',
            name='kind_order_of_service',
            field=models.CharField(choices=[('05', 'AGUARDANDO PEÇAS'), ('02', 'REVISÃO DE EQUIPAMENTOS'), ('9B', 'OUTROS'), ('04', 'FORMATAÇÃO'), ('01', 'LIMPEZA'), ('9A', 'AGUARDANDO TERCEIROS'), ('03', 'REVISÃO DE SERVIÇOS')], max_length=2, verbose_name='tipo do serviço'),
        ),
        migrations.AlterField(
            model_name='service',
            name='call',
            field=models.CharField(choices=[('03', 'EMAIL'), ('02', 'TELEFONE'), ('99', 'OUTROS'), ('05', 'VERBAL'), ('01', 'WHATSAPP'), ('04', 'PRESENCIAL')], default='02', max_length=2, verbose_name='atendimento via'),
        ),
    ]
