# Generated by Django 5.0.6 on 2024-06-27 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_alter_equipment_serial_number'),
        ('reports', '0009_report_service'),
        ('services', '0016_alter_orderofservice_kind_order_of_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofservice',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipments.equipment', verbose_name='equipamento na os'),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='kind_order_of_service',
            field=models.CharField(choices=[('9B', 'OUTROS'), ('9A', 'AGUARDANDO TERCEIROS'), ('01', 'LIMPEZA'), ('05', 'AGUARDANDO PEÇAS'), ('02', 'REVISÃO DE EQUIPAMENTOS'), ('04', 'FORMATAÇÃO'), ('03', 'REVISÃO DE SERVIÇOS')], max_length=2, verbose_name='tipo do serviço'),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reports.report', verbose_name='laudo da os'),
        ),
        migrations.AlterField(
            model_name='service',
            name='call',
            field=models.CharField(choices=[('02', 'TELEFONE'), ('01', 'WHATSAPP'), ('99', 'OUTROS'), ('04', 'PRESENCIAL'), ('05', 'VERBAL'), ('03', 'EMAIL')], default='02', max_length=2, verbose_name='atendimento via'),
        ),
    ]
