# Generated by Django 5.0.3 on 2024-04-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_alter_historyremovaldeliveryequipment_room_and_more'),
        ('reports', '0004_alter_report_options_alter_materialreport_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.equipment', verbose_name='equipamento'),
        ),
    ]
