# Generated by Django 5.0.3 on 2024-05-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='service',
        ),
    ]
