# Generated by Django 5.0.3 on 2024-05-07 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_report_service'),
        ('services', '0013_alter_service_call_orderofservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service', verbose_name='numero do atendimento'),
        ),
    ]
