# Generated by Django 5.0.3 on 2024-03-12 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0007_material_supplier_alter_material_bidding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipment', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='identificação do equipamento')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('patrimony', models.CharField(default='0', max_length=10, verbose_name='patrimonio')),
                ('kind', models.CharField(choices=[('01', 'Computador'), ('02', 'Tablet'), ('03', 'Notebook'), ('04', 'Impressora'), ('05', 'Celular'), ('06', 'Monitor'), ('07', 'Nobreak'), ('08', 'Estabilizador'), ('09', 'Relógio de Ponto'), ('10', 'Switch'), ('11', 'Outros')], default='01', max_length=2, verbose_name='tipo')),
                ('description', models.TextField(verbose_name='descrição')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='setores', to='dashboard.sector', verbose_name='setor')),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
                'ordering': ['id_equipment', 'sector', 'status', 'kind', 'patrimony'],
            },
        ),
        migrations.CreateModel(
            name='HistoryRemovalDeliveryEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_history', models.CharField(max_length=18, verbose_name='historico')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('observation', models.TextField(verbose_name='observação')),
                ('employee', models.CharField(max_length=20, null=True, verbose_name='funcionário')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('charger', models.BooleanField(default=False, verbose_name='carregador')),
                ('props', models.BooleanField(default=False, verbose_name='acessórios')),
                ('delivery', models.BooleanField(default=False, verbose_name='entrega')),
                ('removal', models.BooleanField(default=False, verbose_name='retirada')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipments.equipment', verbose_name='Equipamento')),
                ('pro_accountable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel', to=settings.AUTH_USER_MODEL, verbose_name='tecnico responsavel')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tecnico', to=settings.AUTH_USER_MODEL, verbose_name='tecnico')),
            ],
            options={
                'verbose_name': 'historico',
                'verbose_name_plural': 'historicos',
                'ordering': ['-date', 'status'],
            },
        ),
    ]
