# Generated by Django 5.0.3 on 2024-03-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_historyremovaldeliveryequipment_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyremovaldeliveryequipment',
            name='room',
            field=models.CharField(blank=True, null=True, verbose_name='Sala'),
        ),
    ]
