# Generated by Django 5.0.3 on 2024-03-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_historyremovaldeliveryequipment_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='charger',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='carregador'),
        ),
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='delivery',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='entrega'),
        ),
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='props',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='acessórios'),
        ),
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='removal',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='retirada'),
        ),
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='status'),
        ),
    ]
