# Generated by Django 5.0.3 on 2024-03-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_alter_historyremovaldeliveryequipment_charger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='charger',
            field=models.BooleanField(default=False, verbose_name='carregador'),
        ),
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='entrega'),
        ),
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='number_history',
            field=models.CharField(max_length=30, verbose_name='historico'),
        ),
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='props',
            field=models.BooleanField(default=False, verbose_name='acessórios'),
        ),
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='removal',
            field=models.BooleanField(default=False, verbose_name='retirada'),
        ),
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
