# Generated by Django 5.0.3 on 2024-04-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_alter_historyremovaldeliveryequipment_charger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='id_equipment',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='identificação do equipamento'),
        ),
    ]
