# Generated by Django 5.0.3 on 2024-04-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_material_supplier_alter_material_bidding'),
        ('equipments', '0007_alter_equipment_id_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='room',
            field=models.CharField(blank=True, null=True, verbose_name='sala'),
        ),
        migrations.AlterField(
            model_name='historyremovaldeliveryequipment',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sector', verbose_name='setor'),
        ),
    ]
