# Generated by Django 5.0.3 on 2024-04-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_equipment_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='numero de série'),
        ),
    ]
